In [4]:
import numpy as np

In [8]:
array_of_floats = np.arange(0,2,0.3)

In [9]:
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
#two dimensional array

In [10]:
array_2d = np.array([(2,4,6),(3,5,7)])

In [11]:
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [12]:
array_2d.shape

(2, 3)

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
array_nd = np.arange(6).reshape(2,3)

In [15]:
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
array_nd = np.arange(12).reshape(3,4)

In [17]:
array_nd

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#3-Dimensional Array

In [22]:
z = np.arange(24).reshape(2,4,3)

In [23]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
# 1-Dimensional array

In [26]:
a = np.arange(6)

In [27]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
#2-Dimensional array

In [32]:
c = np.arange(12).reshape(4,3)

In [33]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
c = np.arange(36).reshape(6,6)

In [35]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])