In [1]:
!pip install numpy

In [2]:
!pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1


In [4]:
import numpy as np

array_one = np.array([1,2,3,4])

In [5]:
type(array_one)

numpy.ndarray

In [8]:
numbers  = [10,20,30,40,50]

In [9]:
array_two = np.array(numbers)

In [10]:
array_two

array([10, 20, 30, 40, 50])

In [11]:
x = np.array(numbers)

In [12]:
x

array([10, 20, 30, 40, 50])

In [25]:
array_of_one = np.ones((3,4))

In [26]:
array_of_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
array_of_ones = np.ones((3,4),dtype = np.int16)

In [34]:
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)