In [ ]:
#Numpy

In [1]:
import numpy as np

In [3]:
a = np.array([15,15,15])

b = np.array([10,10,10])

In [4]:
a+b

array([25, 25, 25])

In [5]:
a-b

array([5, 5, 5])

In [6]:
a*b

array([150, 150, 150])

In [7]:
a/b

array([1.5, 1.5, 1.5])

In [10]:
a%b

array([5, 5, 5], dtype=int32)

In [11]:
a<b

array([False, False, False])

In [13]:
a>b

array([ True,  True,  True])

In [14]:
a==b

array([False, False, False])

In [15]:
a**2

array([225, 225, 225], dtype=int32)

In [16]:
b**3

array([1000, 1000, 1000], dtype=int32)

In [17]:
b*=3

In [18]:
b

array([30, 30, 30])

In [19]:
a*10

array([150, 150, 150])

In [ ]:
#b value to 45

In [21]:
b+=a

In [22]:
b

array([45, 45, 45])

In [ ]:
#unary operators

In [23]:
age = np.array([12,15,18,20,26])

In [24]:
age.sum()

91

In [25]:
age.max()

26

In [26]:
age.min()

12

In [27]:
numbers = np.arange(12).reshape(3,4)

In [28]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
numbers.shape

(3, 4)

In [30]:
#sum of each column

In [33]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
numbers.sum(axis=1)

array([ 6, 22, 38])

In [36]:
#statistical Function

In [37]:
test_score =np.array([32.33,52.33,57.33,42.14,87.36,97.12,67.14])

In [38]:
print('Mean test score of the students\n')

print(np.mean(test_score))

Mean test score of the students

62.25


In [39]:
print('Median test score of studens\n')

print(np.median(test_score))

Median test score of studens

57.33


In [40]:
player_runs =np.array([2,45,98,112,57,25,49,87])

In [44]:
print('Mean of Players\n')

print( np.mean(player_runs))

Mean of Players

59.375


In [45]:
print('Median of Players\n')

print( np.median(player_runs))

Median of Players

53.0
